batch_size: 8
crop_size:
- 256
- 256
detection_folders:
- TRA
dropout: 0.01
example_images: False  # Slow
cache: True
input_train:
- ../thesis_misc/CTC_DATA/Fluo-N2DL-HeLa/02
input_val:
- ../thesis_misc/CTC_DATA/Fluo-N2DL-HeLa/01
max_tokens: 2048
name: example
ndim: 2
num_decoder_layers: 1
num_encoder_layers: 1
d_model: 16
outdir: runs
distributed: False
window: 4
features: pretrained_feats
pretrained_feats_model: facebook/sam2.1-hiera-base-plus
pretrained_feats_mode: nearest_patch
pretrained_feats_pca_ncomp: 16
