name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run pre-commit linting
        run: pipx run pre-commit run --all-files
        
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }} with ilp=${{ matrix.ilp }}
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        platform: [ubuntu-latest]
        ilp: ["false"]
        include:
          - platform: windows-latest
            python-version: "3.10"
            ilp: "false"
          - platform: macos-latest
            python-version: "3.10"
            ilp: "false"
          - platform: ubuntu_latest
            python-version: "3.10"
            ilp: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          use-mamba: true
          channels: conda-forge
          channel-priority: true

      - name: Install ilp dependencies
        if: matrix.ilp == 'true'
        run: mamba install -c gurobi -c funkelab ilpy
          
      - name: Install package and dependencies
        run: python -m pip install -e .[test]

      - name: Test
        run: pytest tests -v --color=yes
